jobs:

- job: Deploy
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'npm ci'

  - script: npm run firebase -- emulators:exec "npm test" --project "$FIREBASE_PROJECT"
    displayName: 'npm test (with Firebase emulators)'

  - script: npm run firebase -- deploy --project "$FIREBASE_PROJECT" --token "$FIREBASE_TOKEN"
    displayName: 'Deploy to Firebase'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
